### ISSUE TITLE
Error creating ssdp server: Unable to find a compatible network interface

### ISSUE THREAD

**Issue by mormotion** [armadillica/flamenco-manager-go#3]
time="2017-09-11T07:18:18+10:00" level=warning msg="Flamenco Server URL:https://cloud.blender.org/" 
time="2017-09-11T07:18:18+10:00" level=warning msg="join group 0 operation not supported"
time="2017-09-11T07:18:18+10:00" level=warning msg="join group 2 operation not supported"
time="2017-09-11T07:18:18+10:00" level=fatal msg="Error creating ssdp server: Unable to find a compatible network interface!"

Getting the attached error when I attempt to launch a newly configured manager on a linux machine (xubuntu 16.04). In use network device is a wireless usb dongle.

**Comment by mormotion** [comment]
[mongodb_log.txt](https://github.com/armadillica/flamenco-manager-go/files/1291125/mongodb_log.txt)

**Comment by sybrenstuvel** [comment]
Interesting, probably the wireless USB dongle doesn't support multicast (which is required for UPnP/SSDP autodiscovery). You'll have to disable UPnP/SSDP autodiscovery and manually configure the `manager_url` setting on your Workers.

**Comment by sybrenstuvel** [comment]
The issue in `mongodb_log.txt` shows an indication that the built-in MongoDB server wasn't properly shut down. You can kill it with `killall mongod` if it's the only MongoDB server running on the machine. I'll see if I can make it shut down properly when SSDP fails to start, in a future version of Flamenco Manager.

**Comment by mormotion** [comment]
I was able to start the manager by disabling UPnP/SSDP autodiscovery, as suggested.
Thanks
